In [ ]:
import sklearn
from sklearn import preprocessing

Standardization:  preprocessing.scale()

In [ ]:
from sklearn import preprocessing
import numpy as np
x = np.array([[1, 2, 3],
[ 4,  5,  6],
[ 7,  8, 9]])
y_scaled = preprocessing.scale(x)
print(y_scaled)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


MinMaxScaler(feature_range=(1,5))

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
x = MinMaxScaler(feature_range=(0,8))
y = np.array([[1, 2, 3],
[ 4,  -5,  -6],
[ 7,  8, 9]])
scale = x.fit_transform(y)
scale

array([[0.        , 4.30769231, 4.8       ],
       [4.        , 0.        , 0.        ],
       [8.        , 8.        , 8.        ]])

In [ ]:
from sklearn import preprocessing
import numpy as np
X = [[1,2,3],
[4,-5,-6],
[7,8,9]]
y = preprocessing.normalize(X)
y

array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231, -0.56980288, -0.68376346],
       [ 0.50257071,  0.57436653,  0.64616234]])

[0,1] or [-1,1]

In [ ]:
import sklearn.preprocessing
import numpy as np
enc = preprocessing.OrdinalEncoder()
X = [['a','b','c','d'], ['e', 'f', 'g', 'h'],['i','j','k','l']]
enc.fit(X)
enc.transform([['a', 'f', 'g','l']])

array([[0., 1., 1., 2.]])

In [ ]:
import sklearn.preprocessing
import numpy as np
enc = preprocessing.OneHotEncoder()
X = [['a','b','c','d'], ['e', 'f', 'g', 'h'],['i','j','k','l']]
enc.fit(X)
enc.transform([['a', 'f', 'g', 'l']]).toarray().reshape(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import sklearn.preprocessing 
import numpy as np
X = np.array([[ -3,2,3],
              [-4,-5,6],
              [7,8,9]])
dis = preprocessing.KBinsDiscretizer(n_bins=[3,2,2], encode='ordinal')
dis.fit_transform(X)

array([[1., 1., 0.],
       [0., 0., 1.],
       [2., 1., 1.]])

Discretization:

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
X = [[np.nan, 1,2], [3,4, np.nan], [5, np.nan, 6]]
impute.fit_transform(X)

array([[4. , 1. , 2. ],
       [3. , 4. , 4. ],
       [5. , 2.5, 6. ]])

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
x = np.array([[1,2],
              [3,4]])
nonl = PolynomialFeatures(2)
nonl.fit_transform(x)

array([[ 1.,  1.,  2.,  1.,  2.,  4.],
       [ 1.,  3.,  4.,  9., 12., 16.]])

In [ ]:
import sklearn.preprocessing 
import numpy as np
transformer = preprocessing.FunctionTransformer(np.log1p, validate=True)
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
transformer.transform(X)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509]])

data transformasion 